export const GET_EVENTS_REQUEST = 'GET_EVENTS_REQUEST';
export const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';
export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS';

export const GET_EVENTS_FILTERED_REQUEST = 'GET_EVENTS_FILTERED_REQUEST';
export const GET_EVENTS_FILTERED_ERROR = 'GET_EVENTS_FILTERED_ERROR';
export const GET_EVENTS_FILTERED_SUCCESS = 'GET_EVENTS_FILTERED_SUCCESS';

export const POST_NEW_EVENT_REQUEST = 'POST_NEW_EVENT_REQUEST';
export const POST_NEW_EVENT_SUCCES = 'POST_NEW_EVENT_SUCCES';
export const POST_NEW_EVENT_ERROR = 'POST_NEW_EVENT_ERROR';