export const SET_USER = 'SET_USER';
export const CHECK_FOR_SAVED_USER = 'CHECK_FOR_SAVED_USER';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';

export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST';

export const GET_ALL = 'USER_GET_ALL';
export const GET_ALL_SUCCESS = 'USER_GET_ALL_SUCCESS';
export const GET_ALL_ERROR = 'USER_GET_ALL_ERROR';